### PR TITLE
e2e tests

### PR DESCRIPTION
**Pull request by rpeshkov**
Restoring E2E tests PR

### CODE REVIEW

**Comment by rpeshkov** [comment]
It's weird, but 8e80df9 commit is in each PR now :)
I've merged develop into my branches, but that didn't help.

**Comment by AdrieanKhisbe** [comment]
@rpeshkov You can do an interactive rebase to get rid of it. (and of the Merge remote-tracking)

**Comment by AdrieanKhisbe** [comment]
Original discussion: https://github.com/vscode-org-mode/vscode-org-mode-fork/pull/10

**Comment by sipi** [comment]
@rpeshkov we can merge?

**Comment by rpeshkov** [comment]
@sipi, yep, it can be merged

**Comment by sipi** [comment]
done

**Comment by AdrieanKhisbe** [comment]
super!! :)

**Pull request merged**
