### PR TITLE
Code coverage setup

### PR DESCRIPTION
**Pull request by rpeshkov**
Restoring code coverage PR

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
@rpeshkov Might need to be rebase to solve conflict (and to get ride of 8e80df9 and 747433b)
Once done I thinks it's good to be squashed :)

**Comment by sipi** [comment]
Next one? for the first one who has time to rebase…

**Comment by AdrieanKhisbe** [comment]
> Next one? for the first one who has time to rebase…

What do you mean @sipi ? :)

**Comment by sipi** [comment]
I mean, we should merge this PR. But, we have to fix conflicts before. If anyone have ten minutes to do so…

**Comment by AdrieanKhisbe** [comment]
@sipi that was I thought but was unsure.

I could do it, unfortunately I don't have push (and push force)  right on `rpeshkov:feature/code-coverage` @rpeshkov branch. :/

**Comment by sipi** [comment]
:/

**Comment by rpeshkov** [comment]
> @sipi that was I thought but was unsure.
> 
> I could do it, unfortunately I don't have push (and push force) right on `rpeshkov:feature/code-coverage` @rpeshkov branch. :/

Well, that is expected, since you're trying to push into fork in my account :) Let me quickly resolve conflicts and I'll update this PR

**Comment by AdrieanKhisbe** [comment]
@sipi Shall I squash?

**Comment by sipi** [comment]
done :)

**Pull request merged**
