### PR TITLE
Provides outline-view and improves folding chunks

### PR DESCRIPTION
**Pull request by sipi**
This patch implements a provider for the default outline view. This outline provider is merged with the existing folding provider which is therefore improved with code blocks folding.
And, thanks to @KyrychukD and the magic of [WeakMaps](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap), computed outlines and foldings are kept for all opened documents.

### CODE REVIEW

**Comment by sipi** [comment]
I have a funny issue 🤪 with the really simple document below:
```
* 1
* 2
* 3
* 4
* 5
* 6
* 7
* 8
* 9
* 10
* 11
```

from 11 same level headers, I get a wrong order…  6, 1, 2, 3, 4, 5, 2, 7, 8, 9, 10, 11…
This issue "works" on sub-headers too.

**Comment by sipi** [comment]
I don't really explain this behavior but my outline view was in *Sort By: Type* ! In *Sort By: Position*, all is fine :smile:

**Comment by KyrychukD** [comment]
I can confirm. Outline view behaves the same way with markdown headers, so I don't think this PR is causing the glitch.

**Comment by AdrieanKhisbe** [comment]
> I can confirm. Outline view behaves the same way with markdown headers, so I don't think this PR is causing the glitch.

I can confirm also, glitch is happening also for markdown.

Do you know @dmytrokyrychuk if some issue on vscode has been opened?

**Comment by sipi** [comment]
for history: https://github.com/vscode-org-mode/vscode-org-mode-fork/pull/2

**Pull request merged**
